pipeline {
    agent any

    environment {
        ALLURE_REPORTS = "target/allure-results"
    }

    stages {
         stage('Run Tests') {
            steps {
                sh 'mvn clean test'
            }
            post {
                always {
                    archiveArtifacts artifacts: 'target/allure-results/**', fingerprint: true
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                script {
                    allure([
                        results: [[path: "target/allure-results"]]
                    ])
                }
            }
        }
    }

    post {
        always {
            emailext subject: "Test Execution Report",
                     body: "Allure report available at ${BUILD_URL}/allure/",
                     recipientProviders: [developers()]
        }
    }
}
