pipeline {
    agent any

    environment {
        ALLURE_RESULTS = "target/allure-results"
    }

    parameters {
        booleanParam(name: 'GENERATE_ALLURE', defaultValue: true, description: 'Generate Allure Report')
    }

    stages {
        stage('Run Tests') {
            steps {
                sh 'mvn clean test'
            }
            post {
                always {
                    archiveArtifacts artifacts: 'target/allure-results/**', fingerprint: true
                }
            }
        }

        stage('Generate Allure Report') {
            when {
                expression { return params.GENERATE_ALLURE == true }
            }
            steps {
                script {
                    allure([
                        results: [[path: "target/allure-results"]]
                    ])
                }
            }
        }
    }

    post {
        success {
            script {
                echo "Allure report is available at: ${BUILD_URL}allure/"
            }
        }
    }
}
