pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Выполнение сборки Maven
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Запуск тестов Maven
                    sh 'mvn test'
                }
            }
        }
    }
}
